# Generated by Django 5.2.1 on 2025-05-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('red', 'Красный'), ('green', 'Зелёный'), ('blue', 'Синий')], default='red', max_length=20, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], default='M', max_length=5, verbose_name='Размер'),
        ),
    ]
