# Generated by Django 4.2.21 on 2025-06-01 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_category_alter_product_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
